### ISSUE TITLE
New Component - Tooltip 

### ISSUE THREAD

**Issue by karishmashuklaa** [karishmashuklaa/chic-ui#101]
Positions - left, right, top, bottom

**Comment by BurhanRaja** [comment]
Hello @karishmashuklaa 
Can I contribute to this issue?
Please assign it to me.

**Comment by BurhanRaja** [comment]
Thank you.

**Comment by BurhanRaja** [comment]
There is a problem.
Actually, what is happening is after npm install all the dependencies are installed but when I open any tsx file, it is throwing me error and asking to update them, so should I update them? Is it ok?

**Comment by karishmashuklaa** [comment]
Hi. Couldn't reproduce the npm install error.
Could you connect with me on Discord - carishma#3453

**Comment by BurhanRaja** [comment]
Yaa sure.
