### ISSUE TITLE
Feature - Add options to Progress Bar component

### ISSUE THREAD

**Issue by talis-fb** [karishmashuklaa/chic-ui#105]
It'd be nice a type props for make the bar with stripes or not. Furthermore, add options to make the bar animated or not. If it's possible I'd like to be assigned to this =D

**Comment by karishmashuklaa** [comment]
@talis-fb Hello. We currently have `type` prop for progress bars of different colors - see <a href="https://chic-ui.vercel.app/docs/components/progress-bar#api">here</a>
Instead we can have a prop `striped` which will be a boolean. If true it will add stripes to the progress bar :D

**Comment by talis-fb** [comment]
Awesome! I rename the issue to fix it then
