### ISSUE TITLE
Add Alert Component 

### ISSUE THREAD

**Issue by karishmashuklaa** [karishmashuklaa/chic-ui#19]

**Comment by AneeqaKhan** [comment]
Hi @karishmashuklaa I want to work on it

**Comment by karishmashuklaa** [comment]
@AneeqaKhan Sure! Just go through the Contribution guidelines in **[CONTRIBUTING.md](https://github.com/karishmashuklaa/chic-ui/blob/master/CONTRIBUTING.md)**
Also star the repository if you like it! Thank you 😄

**Comment by 309666** [comment]
Hi @karishmashuklaa I would like to work on it

**Comment by sims-keshri** [comment]
I would like to work on it

**Comment by karishmashuklaa** [comment]
@AneeqaKhan Please update me with the progress. If you are unable to work on it I can assign it to someone else :)

**Comment by AneeqaKhan** [comment]
sorry, I didn't get time to work on it and update you as well. Please feel free to assign it to someone else :)

**Comment by karishmashuklaa** [comment]
@AneeqaKhan No problem! :D
