### ISSUE TITLE
Add Progress Bar Component

### ISSUE THREAD

**Issue by karishmashuklaa** [karishmashuklaa/chic-ui#20]

**Comment by kvnal** [comment]
I would like to work on this, Please assign me this task

**Comment by karishmashuklaa** [comment]
@kvnal  Sure! Just go through the Contribution guidelines in **[CONTRIBUTING.md](https://github.com/karishmashuklaa/chic-ui/blob/master/CONTRIBUTING.md)**

Keep me updated with your progress.

Also star the repository if you like it! Thank you 😄

**Comment by kvnal** [comment]
PR created pls review #38 👈.
Thanks🌟!

**Comment by kvnal** [comment]
@karishmashuklaa Conflicts Resolved and PR changed to `features`. pls review. Thanks

**Comment by karishmashuklaa** [comment]
@kvnal Thanks for contributing! 🎉

**Comment by karishmashuklaa** [comment]
@kvnal Yes it is. You can discuss with me here. I might be a little slow to respond due to college, but yes feel free to drop your suggestions!

**Comment by kvnal** [comment]
> @kvnal Yes it is. You can discuss with me here. I might be a little slow to respond due to college, but yes feel free to drop your suggestions!

Sure @karishmashuklaa !!

here are some >>
**More cool components to be added** 
📌Modal / Dialog Box
📌List (<ul></ul>) with custom icons
📌Alert (with vanish time)
📌 Circular Progress Bar
📌 Spinner
📌 Side Bar drawer

**Comment by karishmashuklaa** [comment]
@kvnal All of the components except List have already been added / being worked on. Let me know if you want to work on the List component.

**Comment by kvnal** [comment]
> @kvnal All of the components except List have already been added / being worked on. Let me know if you want to work on the List component.

Sounds good @karishmashuklaa 🙌! pls create the issue and assign it to me, so that I may begin working on it.

**Comment by karishmashuklaa** [comment]
@kvnal Are you still up for it? Should I create an issue?

**Comment by kvnal** [comment]
> @kvnal Are you still up for it? Should I create an issue?

sure! why not
