### ISSUE TITLE
Add Breadcrumb Component

### ISSUE THREAD

**Issue by karishmashuklaa** [karishmashuklaa/chic-ui#21]

**Comment by PiperGuy** [comment]
I would like to work on this component please assign it to me.

**Comment by karishmashuklaa** [comment]
@PiperGuy  Sure! Just go through the Contribution guidelines in **[CONTRIBUTING.md](https://github.com/karishmashuklaa/chic-ui/blob/master/CONTRIBUTING.md)**

Keep me updated with your progress.

Also star the repository if you like it! Thank you 😄
