### ISSUE TITLE
Add Switch Component

### ISSUE THREAD

**Issue by karishmashuklaa** [karishmashuklaa/chic-ui#22]

**Comment by rahulbhatt1899** [comment]
Hey, could you provide some more information about this issue, I'd like to contribute!

**Comment by karishmashuklaa** [comment]
Hey @rahulbhatt1899! 
For starters, you can build a toggle switch component with the following props
- `size` - ranging from small to extra-large
- `type` - different colors like success, danger etc. Similar to the existing Button Component.
- `checked` and `unchecked` 
- `disabled` 

Even if you work on just the sizing and types, that will be fine.

**Comment by maciej-plonka** [comment]
Hi @rahulbhatt1899 and @karishmashuklaa , can I work on this issue?

**Comment by karishmashuklaa** [comment]
@maciej-plonka Sure you can discuss with @rahulbhatt1899 else you can work on another component. I can create an issue and assign it to you.

**Comment by DoubleNemesis** [comment]
Hey I see you have some takers for this, but if you have any other issues coming up, I'd happily be involved

**Comment by karishmashuklaa** [comment]
@DoubleNemesis Hey there! I've added some new issues, do check :)

**Comment by DoubleNemesis** [comment]
@karishmashuklaa just realised it's all typescript and I don't know typescript. Should have read CONTRIBUTING.md before offering. Sorry!

**Comment by amhsirak** [comment]
@DoubleNemesis No problem. Thank you!

**Comment by maciej-plonka** [comment]
@karishmashuklaa I am still up for being assigned to the issue :)

**Comment by amhsirak** [comment]
@maciej-plonka Sure! Go ahead 💯 Just go through the Contribution guidelines in **[CONTRIBUTING.md](https://github.com/karishmashuklaa/chic-ui/blob/master/CONTRIBUTING.md)**
