### ISSUE TITLE
Add Tooltip Component 

### ISSUE THREAD

**Issue by karishmashuklaa** [karishmashuklaa/chic-ui#23]
Create a tootlip component which has the following props:
- `label` - For the text content
- `children` 
- `position` - top | right | bottom | left

If you have any ideas on what else can be done, drop it here!

**Comment by ManuelMartinDev** [comment]
Hi!, I would like to take care of this issue :)

**Comment by karishmashuklaa** [comment]
@ManuelMartinDev Sure! Just go through the Contribution guidelines in **[CONTRIBUTING.md](https://github.com/karishmashuklaa/chic-ui/blob/master/CONTRIBUTING.md)**

Keep me updated with your progress.

Also star the repository if you like it! Thank you 😄
