### ISSUE TITLE
Add Checkbox Component 

### ISSUE THREAD

**Issue by karishmashuklaa** [karishmashuklaa/chic-ui#24]
Create a Checkbox component which has the following props for starters:
- `label` - For the text content
- `type` - different colors like success, danger etc. Similar to the existing Button Component. Type should change the color of the checkbox when checked.

If you have any ideas on what else can be done, drop it here!

**Comment by MuhammadTanveer94** [comment]
@karishmashuklaa i would loved to do this. Please assign me this issue.

**Comment by karishmashuklaa** [comment]
@MuhammadTanveer94  Sure! Just go through the Contribution guidelines in **[CONTRIBUTING.md](https://github.com/karishmashuklaa/chic-ui/blob/master/CONTRIBUTING.md)**

Keep me updated with your progress.

Also star the repository if you like it! Thank you 😄

**Comment by 309666** [comment]
@karishmashuklaa I am fresher, i want to work on it please assign me.

**Comment by karishmashuklaa** [comment]
@MuhammadTanveer94  Please update me with the progress. If you are unable to work on it I can assign it to someone else :)
