### ISSUE TITLE
Add Drawer Component 

### ISSUE THREAD

**Issue by karishmashuklaa** [karishmashuklaa/chic-ui#25]

**Comment by Morialkar** [comment]
Hi! I'd like to take this one, can we discuss a tad on what you're expecting from this component, what kind of properties we want to offer to users etc...

**Comment by karishmashuklaa** [comment]
Hey @Morialkar! I was thinking maybe we can add a component named Drawer/Sidebar which is responsive and opens from the left or right side of the page. If you have any ideas, drop them here

**Comment by Morialkar** [comment]
Sounds good. In terms of properties, I'm thinking of:
- side (left/right)
- width
- showButton (to display an open/close button on hover, kinda like in Jira)
- backgroundColor

and allow children to populate the Drawer

**Comment by karishmashuklaa** [comment]
@Morialkar Amazing! go ahead! 💯 
Just go through the Contribution guidelines in **[CONTRIBUTING.md](https://github.com/karishmashuklaa/chic-ui/blob/master/CONTRIBUTING.md)**

Keep me updated with your progress.

Also star the repository if you like it! Thank you 😄

**Comment by karishmashuklaa** [comment]
@Morialkar  Please update me with the progress. If you are unable to work on it I can assign it to someone else :)
