### ISSUE TITLE
Add Navbar Component 

### ISSUE THREAD

**Issue by karishmashuklaa** [karishmashuklaa/chic-ui#26]

**Comment by ayasahmad63** [comment]
I love to work on it, pls assign it to me

**Comment by karishmashuklaa** [comment]
@ayasahmad63  Sure! Just go through the Contribution guidelines in **[CONTRIBUTING.md](https://github.com/karishmashuklaa/chic-ui/blob/master/CONTRIBUTING.md)**

Keep me updated with your progress.

Also star the repository if you like it! Thank you 😄

**Comment by ayasahmad63** [comment]
pls, deassign this as I am not able to do it. sry

**Comment by ankeshp03** [comment]
Hi, if it is not assigned, can you please assign this to me?

**Comment by karishmashuklaa** [comment]
@ankeshp03 Sure, go ahead! 💯 
Just go through the Contribution guidelines in **[CONTRIBUTING.md](https://github.com/karishmashuklaa/chic-ui/blob/master/CONTRIBUTING.md)**

Keep me updated with your progress.

Also star the repository if you like it! Thank you 😄

**Comment by ankeshp03** [comment]
Sure. Thanks. 😊

**Comment by ankeshp03** [comment]
Hi @karishmashuklaa, I have completed 4 hacktoberfest projects.
Since this is hacktober accepted project, if someone else wants to work on this, please assign it.

**Comment by henckellbach** [comment]
Hey, I would love to work on this one. Are there any specific plans for this one?
