### ISSUE TITLE
Add Badge Component (and rename Badge to Tag)

### ISSUE THREAD

**Issue by henckellbach** [karishmashuklaa/chic-ui#28]
Hey! I would like to add a Badge component which displays a count or just a colored dot overlayed over its children. The old Badge component should be renamed to Tag as its more descriptive of its use.

![image](https://user-images.githubusercontent.com/22558663/135707947-2b846019-8eb7-4aca-b0b6-3cad5e29aa3d.png)

The component should take these props:
- `count: number` - number to display in the badge
- `limit: number` - the maximum count after which we get something like 99+
- `type: 'default' | 'secondary' | 'danger' | 'warning' | 'success'| 'light'` - color
- `size: number` - the size in px
- `shouldDisplayZero: boolean` - badge should render even if `count === 0`
- `shouldDisplayCount: boolean` - should render count or just an empty dot
- `offset: [number, number]` - x and y offset in px

---

Question: What are your naming conventions for boolean props? I am personally not a fan of `disabled` or `error` when compared to `isDisabled` and `hasError`. Looking for your suggestions for the two boolean props here (`showZero` vs `shouldDisplayZero` etc.)

**Comment by karishmashuklaa** [comment]
@henckellbach Hello, love your insights! Yes we can rename the current Badge component to Tag. Currently, Avatars can be given a `hasBadge` prop which only allows green color. I think we can make use of this Badge component instead!

Answer: I actually agree with you but when I started working on this project, I went with props `disabled` and `error`. So to keep it consistent  you can proceed with `showZero` and `shouldDisplayZero`

**Comment by henckellbach** [comment]
Awesome! Thanks for the quick reply, I will start working on this in the coming days 🎉

**Comment by karishmashuklaa** [comment]
@henckellbach Sure! Keep me updated 💯

**Comment by henckellbach** [comment]
Opened a PR - https://github.com/karishmashuklaa/chic-ui/pull/58
