### ISSUE TITLE
Pagination component

### ISSUE THREAD

**Issue by ManuelMartinDev** [karishmashuklaa/chic-ui#31]
I think it would be cool to work in a pagination component, it could take props for:

- decide if you want the prev/next page to be buttons or arrows
- decide how many page buttons to display
- decide if you want to move between pages using buttons with page number or otherwhise use text input to write the page
- some color props to give style to the page buttons

I could work on this

**Comment by karishmashuklaa** [comment]
@ManuelMartinDev Sure go ahead. For color make a prop named - `type: 'default' | 'secondary' | 'danger' | 'warning' | 'success'| 'light'` (use same colors as the Button Component )
