### ISSUE TITLE
Slider Component

### ISSUE THREAD

**Issue by sivantha96** [karishmashuklaa/chic-ui#34]
What do you think about having a slider component?

This allows the selection of values from a range via mouse, touch, or keyboard, similar to `<input type="range">`

something like this?

![1b9e4be5acadd82f77d5cf66f16cfe50](https://user-images.githubusercontent.com/37335828/135721574-69bc244f-682f-471f-b83a-84f8be084236.gif)

I could work on this.

**Comment by karishmashuklaa** [comment]
@sivantha96 Hey, sure go ahead 💯 
Add a prop named `type: 'default' | 'secondary' | 'danger' | 'warning' | 'success'| 'light'` - for color of the slider

Just go through the Contribution guidelines in **[CONTRIBUTING.md](https://github.com/karishmashuklaa/chic-ui/blob/master/CONTRIBUTING.md)**

Keep me updated with your progress.

Also star the repository if you like it! Thank you 😄

**Comment by sivantha96** [comment]
It would be great if you could add hacktoberfest labels for this.
