### ISSUE TITLE
Proposal for theme structure

### ISSUE THREAD

**Issue by ManuelMartinDev** [karishmashuklaa/chic-ui#41]
Hi, right now each person is doing copy-paste of the secondary, danger, warning, success, light themes in their own component, if the colors change in the future all the components would need to be modified.
I think the best solution is create a theme file with the theme object that everyone can import in their components.
If you agree with it, I can start working on the refactor

**Comment by karishmashuklaa** [comment]
@ManuelMartinDev You just read my mind :P I was thinking of doing this and working on a grid system. I'll be more than happy to have you work on this! Go ahead 💯
