### ISSUE TITLE
Website Frontend

### ISSUE THREAD

**Issue by Nikhil27b** [karishmashuklaa/chic-ui#44]
how I can contribute to your website frontend in Chic UI

**Comment by karishmashuklaa** [comment]
@Nikhil27b Hey there! Currently the documentation of Chic UI hasn't been open-sourced as there is a lot of data to be added.
If you are looking for website frontend designing, you can check out my other project [Tech Net](https://github.com/karishmashuklaa/technet) 
Thank you! 😄
