### ISSUE TITLE
Add Select Component

### ISSUE THREAD

**Issue by mohan-murali** [karishmashuklaa/chic-ui#46]
Add a select component that takes a list and an onChange function as input and returns a drop-down select component. We can further extend this to make an auto-complete/filterable select component. I would like to work on this.

**Comment by karishmashuklaa** [comment]
@mohan-murali Greatt! Go ahead 💯 
Just go through the Contribution guidelines in **[CONTRIBUTING.md](https://github.com/karishmashuklaa/chic-ui/blob/master/CONTRIBUTING.md)**

Keep me updated with your progress.

**Comment by mohan-murali** [comment]
PR created for this. https://github.com/karishmashuklaa/chic-ui/pull/50. Kindly review :)
