### ISSUE TITLE
Discussion: Making SearchBar flush with Search-Button

### ISSUE THREAD

**Issue by syentix** [karishmashuklaa/chic-ui#59]
I was checking out the existing Components and wanted to put it our there for discussion, if it would be nicer to make the right side of the search bar flush with the Search-Button?

Changing the border-radius on the bar and the button would be necessary then.

Just asking if it would be a good idea?

**Comment by syentix** [comment]
#60 is the pr

**Comment by karishmashuklaa** [comment]
@syentix Closed as I have expected your PR. Thank you! 😄
