### ISSUE TITLE
Add dialog / Modal component

### ISSUE THREAD

**Issue by PiperGuy** [karishmashuklaa/chic-ui#62]
Hey @karishmashuklaa Let me what you think about creating a modal/dialog component with header and footer customization. If you are interested please assign it to me

**Comment by karishmashuklaa** [comment]
@PiperGuy Sure! You can work on it

**Comment by AneeqaKhan** [comment]
@PiperGuy are you still working on it? If not, I want to pick it.

**Comment by PiperGuy** [comment]
@AneeqaKhan please pick it up.

**Comment by karishmashuklaa** [comment]
@AneeqaKhan you can proceed 👍

**Comment by AneeqaKhan** [comment]
Thank you!

**Comment by sowrovsarkar63** [comment]
@AneeqaKhan  Did You Work On This?

**Comment by AneeqaKhan** [comment]
Nop, unfortunately I have not

**Comment by karishmashuklaa** [comment]
@AneeqaKhan Unassigning due to inactivity.

**Comment by karishmashuklaa** [comment]
Closing cause it is very stale.
