### ISSUE TITLE
Add Notification Component

### ISSUE THREAD

**Issue by syentix** [karishmashuklaa/chic-ui#66]
I could add a little Notification Pop-Up which appears at the bottom right/left side and can be closed with the X-Button.

**Comment by karishmashuklaa** [comment]
@syentix Similar to a toast component? Go ahead 💯

**Comment by Dgiulian** [comment]
Hi, It seems that no progress was done on this issue, I would like to give it a go if I can

**Comment by syentix** [comment]
Go ahead, i'm kind of busy. I made a base component, couldn't do much more so far. I'm also quite new to styled-components.

**Comment by karishmashuklaa** [comment]
@Dgiulian Go ahead 💯
