### ISSUE TITLE
Discussion: Devops

### ISSUE THREAD

**Issue by PiperGuy** [karishmashuklaa/chic-ui#67]
Hey @karishmashuklaa, Would you be interested in creating Github actions for CI/CD pipeline. I would be able to help with that. If you have any idea about this already let me know. 

my Idea,
- Using GitHub pages for now for deployment. 
- Basic unit tests for all components will run before deployment.

Unit tests can be added eventually but if the pipeline is set up it will be easy to move forward.

What's your thought on this?

**Comment by karishmashuklaa** [comment]
@PiperGuy Good idea! Please contact me on [LinkedIn](https://www.linkedin.com/in/karishma-shukla-138b661bb/) for discussion
