### ISSUE TITLE
Feature - Add `type` prop to Link component

### ISSUE THREAD

**Issue by karishmashuklaa** [karishmashuklaa/chic-ui#97]
Currently, `Link` Component has a hard coded color.
Instead, pass a prop `type` based on existing <a href="https://github.com/karishmashuklaa/chic-ui/blob/dev/src/tokens/themes.ts">theme.</a>

**Comment by raji2004** [comment]
I would love to be assigned this issue

**Comment by FlynnFc** [comment]
Hi, assumed this was inactive so just put up a pr for it
