### ISSUE TITLE
classname prop

### ISSUE THREAD

**Issue by NishantDevs** [karishmashuklaa/chic-ui#99]
for custom styling as I told  @karishmashuklaa a few days ago.

**Comment by karishmashuklaa** [comment]
@NishantDevs do docs as well. Hacktober or skip?

**Comment by NishantDevs** [comment]
@karishmashuklaa skip - I am a genuine fan 😄

**Comment by NishantDevs** [comment]
@karishmashuklaa Can see very well 😄

**Comment by karishmashuklaa** [comment]
ref #134
